### Add new comment
POST http://localhost:3001/posts/2/comments HTTP/1.1
Content-Type: application/json

{
    "user_id" : 1,
    "comment_content": "Updated new comment content"
}


### Delete a post
DELETE http://localhost:3001/posts/1 HTTP/1.1
Content-Type: application/json

### Delete a comment
DELETE http://localhost:3001/posts/1/comments/2 HTTP/1.1
Content-Type: application/json

### Post a new post
POST http://localhost:3001/posts HTTP/1.1
Content-Type: application/json

{
    "user_id": 2,
    "post_content": "Test from REST Client"
}